### ISSUE TITLE
Crash on using //count

### ISSUE THREAD

**Issue by Montandalar** [sbrl/Minetest-WorldEditAdditions#100]
### System info

Minetest version: 5.8.0-dev-5cd6a22d (self-compiled under Debian).
Lua runtime: LuaJIT

### Steps to reproduce

1. Place pos1 with //pos1 at non-integer coordinates. The selection appears where the player stood, not aligned to the node like standard worldedit.
2. Place pos2 with //pos2, no restriction on placement is necessary.
3. Run //count. The game crashes with this error message:

```
AsyncErr: Lua: Runtime error from mod 'worldeditadditions_commands' in callback on_chat_message(): ...test-WorldEditAdditions/worldeditadditions/lib/count.lua:29: table index is nil
stack traceback:
	...test-WorldEditAdditions/worldeditadditions/lib/count.lua:29: in function 'count'
	...Additions/worldeditadditions_commands/commands/count.lua:26: in function 'func'
	...itAdditions/worldeditadditions_core/core/run_command.lua:9: in function 'run_command_stage2'
	...itAdditions/worldeditadditions_core/core/run_command.lua:53: in function 'run_command'
	...itions/worldeditadditions_core/core/register_command.lua:57: in function 'func'
	/usr/local/share/minetest/builtin/game/chat.lua:79: in function </usr/local/share/minetest/builtin/game/chat.lua:52>
	/usr/local/share/minetest/builtin/game/register.lua:446: in function </usr/local/share/minetest/builtin/game/register.lua:432>
```
4. For contrast, re-run the test but in steps 1 and 2, teleport the player to integer coordinates while fly and noclip before running each command. No crash with only integer coordinates.

### Remarks

It is probably necessary to clamp the positions to the nearest node boundaries when running the check. I'm new to this mod though and don't know why non-block-aligned positions would be useful.

**Comment by VorTechnix** [comment]
> It is probably necessary to clamp the positions to the nearest node boundaries when running the check. I'm new to this mod though and don't know why non-block-aligned positions would be useful.

Sorry for your rough introduction to our mod. We just implemented a fancy new selection system that *apparently* still has some bugs.

To clarify all positions *should* be aligned to node as they are in worldedit.
