### ISSUE TITLE
Only a piece of region is removed when hitting it

### ISSUE THREAD

**Issue by Zughy** [sbrl/Minetest-WorldEditAdditions#102]
From the multipoint update. It's very frustrating to remove :(

More info about the video: just logged in, created a region through `//pos1` and `//pos2`, then pressed "record"
MT 5.7

https://github.com/sbrl/Minetest-WorldEditAdditions/assets/63455151/cedb008a-068c-41d3-a38a-328108f643bc

**Comment by sbrl** [comment]
Fix, just preparing a release.
