### ISSUE TITLE
pos1 and pos2 nodes can't be removed if the world is not in creative

### ISSUE THREAD

**Issue by Zughy** [sbrl/Minetest-WorldEditAdditions#103]
Latest release  

I've got all the privs, `creative` included, but I can remove them only if the creative is enabled in the world

**Comment by sbrl** [comment]
For reference, we're working in this branch: [fix-markerdupes](https://github.com/sbrl/Minetest-WorldEditAdditions/tree/fix-markerdupes)

**Comment by sbrl** [comment]
Fixed it! Doing (another) release.
