### ISSUE TITLE
Chat message API w/colour support

### ISSUE THREAD

**Issue by VorTechnix** [sbrl/Minetest-WorldEditAdditions#108]
To provide colorful messages and feedback to users.

**Comment by sbrl** [comment]
We need to replace `worldedit.player_notify(player_name, msg)`, and what better time to also implement some kinda colour API? It would be nice if WorldEditAdditions chat messages had their own colour, and we had a consistent visual language (which would need documenting e.g. in [CONTRIBUTING.md](https://github.com/sbrl/Minetest-WorldEditAdditions/blob/main/CONTRIBUTING.md)!) to enhance what are currently quite challenging chat messages to grok at a glance.

**Comment by VorTechnix** [comment]
A consistent visual language for our player feedback could be the best thing since cloud wand :grin:

**Comment by VorTechnix** [comment]
#116
