### ISSUE TITLE
//walls cmd

### ISSUE THREAD

**Issue by Miniontoby** [sbrl/Minetest-WorldEditAdditions#12]
Please make a new cmd 

Name: walls
Command: //walls
Param: <blockname>
Function: Make inside the selected area (//1 and //2) an wall; just a kind of an //hollowcube but with no top and no bottom.

Example: //walls stone

**Comment by sbrl** [comment]
Thanks for opening the issues, @Miniontoby!

Sure, these seem doable. I'll see what I can :-)

#13 looks like the more challenging one to do out of the 2.

**Comment by sbrl** [comment]
Done! :D
