### ISSUE TITLE
Crash: Attempt to call field 'register_command' (a nil value)

### ISSUE THREAD

**Issue by AFCMS** [sbrl/Minetest-WorldEditAdditions#16]
ModError: Failed to load and run script from C:\Users\Util7\Documents\Louis\minetest-5.2.0-win64\bin\..\mods\worldeditadditions\worldeditadditions_commands\init.lua:
...tions\worldeditadditions_commands/commands/floodfill.lua:6: attempt to call field 'register_command' (a nil value)
stack traceback:
	...tions\worldeditadditions_commands/commands/floodfill.lua:6: in main chunk
	[C]: in function 'dofile'
	...\worldeditadditions\worldeditadditions_commands\init.lua:20: in main chunk
Voir debug.txt pour plus d'informations.

**Comment by sbrl** [comment]
Hey there! Thanks for opening this issue.

As I mention in [the FAQ](https://github.com/sbrl/Minetest-WorldEditAdditions#troubleshooting), WorldEditAdditions requires that [WorldEdit](https://github.com/Uberi/Minetest-WorldEdit/) is installed and up-to-date.

Could you check that you have installed the latest version of WorldEdit please?

**Comment by sbrl** [comment]
I'm going to close this now, but if you're still experiencing issues please comment again here and I'll reopen the issue.
