### ISSUE TITLE
Not possible to use //y in normal worldedit

### ISSUE THREAD

**Issue by Niwla23** [sbrl/Minetest-WorldEditAdditions#2]
I have this mod activated with WE and when I trie to do //r node1 node2, it says i shall type //y.
Then i get: No Operation Pending! This only happens when this mod is active.

**Comment by sbrl** [comment]
Hey! Thanks for the report.

I've run into that one a few times already, but I've been having some trouble tracking it down.

I'll take another look and see what I can do.

**Comment by sbrl** [comment]
Fixed & released!

Looks like I forgot to update this issue & close it :P
