### ISSUE TITLE
attempt to call field 'alias_command' (a nil value)

### ISSUE THREAD

**Issue by rusty-snake** [sbrl/Minetest-WorldEditAdditions#21]
```
ERROR[Main]: ModError: Failed to load and run script from /home/user/.minetest/mods/worldeditadditions/worldeditadditions_commands/init.lua:
ERROR[Main]: .../worldeditadditions/worldeditadditions_commands/init.lua:40: attempt to call field 'alias_command' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]:    .../worldeditadditions/worldeditadditions_commands/init.lua:40: in main chunk
ERROR[Main]: Check debug.txt for details.
```

Minetest: 5.3.0 (flatpak)
WE: latest from ContentDB
WEA: latest from ContentDB

**Comment by sbrl** [comment]
Hey there, @rusty-snake! Sorry that you've encountered a crash. I'll need some more information though to debug the issue.

1. Is the crash on startup?
2. If not, could you detail some precise reproduction steps please?

**Comment by rusty-snake** [comment]
On startup.

**Comment by sbrl** [comment]
Oh my! I thought I'd fixed that one. Let me take a look.

**Comment by rusty-snake** [comment]
f3c6329 seems to work.

**Comment by sbrl** [comment]
Awesome! Glad it works :D

I'm just in the process of putting out a release - there are multiple places I need to post so might take a moment lol :P

Seems like the issue was due to a race condition as I didn't properly depend on `worldedit_shortcommands`, which provides that method.
