### ISSUE TITLE
Feature Suggestion: //line

### ISSUE THREAD

**Issue by VorTechnix** [sbrl/Minetest-WorldEditAdditions#25]
I would like to see line and ramp creation functionality (with variable thickness) added to this awesome mod. I wish I knew enough lua to fork the project and add the feature myself but sadly I don't.

**Comment by sbrl** [comment]
Hey there, @VorTechnix! That sounds like a great idea. How would you see the command working? Perhaps you could give some example invocations of how it would work? Personally, I think this would work nicely:

```
//line <thickness_x> [<thickness_y>]
```

...Where `<thickness_y>` is optional, and is set to the value of `<thickness_x>` if not specified.

**Comment by sbrl** [comment]
I was feeling inspired, so I added it for you, @VorTechnix. Hope it works as intended. If you've got any more suggestion or you find a bug, please open a new issue :-)

**Comment by VorTechnix** [comment]
Thank you so much I'll try it out and let you know how it works for me.
