### ISSUE TITLE
Point Cloud Selection

### ISSUE THREAD

**Issue by VorTechnix** [sbrl/Minetest-WorldEditAdditions#31]
Here is the separate issue for 5 and 6 point cloud selections.

To Reiterate, the idea is to create a standard 2 point selection big enough to encompass a target using 5-6 points selected on that target.

The basic working of the feature would be to simply find the minimum x y and z values of the 5 or 6 point cloud and assign them to the first point of the 2 point (normal) selection, then take the maximum x y and z values of the point cloud and assign them to point 2 of the normal selection.

Moreover, you brought up the idea of making a wand to assist with the task. I'm not sure how you would implement that especially for the case where one point needs to be moved but I'm sure you'll come up with an idea about that.

As for the actual invocation command I'm thinking `//cloudset [re-set number (1-6)]`. My other idea was `//pc set [re-set number (1-6)]`. As always let me know if you have any questions.

**Comment by sbrl** [comment]
In theory, such a wand would work like this:

 - Left click: Add point
 - Right click: Clear all points

This way, we'd be able to use an arbitrary number of points. In addition, we wouldn't even have to store them - just use each successive point to expand the defined region.

**Comment by VorTechnix** [comment]
I actually like that idea a lot. We could place as many points as we want and simply clear them if we screw up.

**Comment by sbrl** [comment]
Implemented!
