### ISSUE TITLE
//overlay on water

### ISSUE THREAD

**Issue by VorTechnix** [sbrl/Minetest-WorldEditAdditions#38]
The overlay command will overlay on top of water nodes. That can be useful sometimes but when creating marshes, fields, papyrus stands or other stuff it is rather annoying:
![2021-03-01 13_41_49-Minetest 5 3 0  OpenGL 4 6 0](https://user-images.githubusercontent.com/45538536/109563115-2d60d000-7a94-11eb-9ea7-0bd084c46f6f.png)
My suggestion is to make add and option to make the command hydrophobic or make a separate command that is.

**Comment by sbrl** [comment]
Oh, this is a great spot. I've recently fixed `//fillcaves` and `//conv` to work underwater, but I wasn't aware that `//overlay` was affected as well. I'll fix this now.

With `worldeditadditions.is_liquidlike()`, I'll fix it not to place nodes on top of *any* liquid.
