### ISSUE TITLE
Cloud Select again

### ISSUE THREAD

**Issue by VorTechnix** [sbrl/Minetest-WorldEditAdditions#43]
The name cloud wand is a bit confusing especially since there's a cloud mod. I move to change the name to Add Selection Wand or Cloud Select Wand or something.

Secondly as with the main world edit select wand there should be a chat command to do the same job. I plan to implement this as `//scloud <1...6>`.

**Comment by sbrl** [comment]
Hrm. Maybe "Additive Selection Wand"? It doesn't have the same ring to it.

Can you elaborate on how an `//scloud <1...6>` command would work? It seems at first glance that it would be more cumbersome to me.

**Comment by VorTechnix** [comment]
0-6 refers to the number is nodes you can punch to add to the selection before you have to run the command again. 0/stop cancels the operation if you still have nodes left but are done with the command.
