### ISSUE TITLE
Repository Enhancements and Management

### ISSUE THREAD

**Issue by VorTechnix** [sbrl/Minetest-WorldEditAdditions#46]
I had a few ideas about how to keep the repository and development streamlined going forward.

## Labels
I would like to propose 3 new labels for issues:
- In Process (orange) -- To denote that the developer (you) or a contributor (me or someone else) is working on the issue.
- Delayed (burgundy) -- To denote that development/debugging has stalled or been delayed (like teeth of time?)
- Meta (very light grey) -- For issues like this that are about the repository or code organization itself.

## Branches
As previously stated I will open my own development branch for continued contributions. I would like to go further though and propose a general management system:

1. The master branch should be the primary and default branch. I understand some of the reasons you decided to change it but having also changed it on other repos I manage I know from experience that it usually just leads to confusion and mix ups.
2. We should have a testing branch that all of our changes and any pull requests from contributor's forks get staged in until we are ready to release the next version. Some people create a new branch for every version but I think that's too much work and sticking with one permanent testing/staging branch gives people the opportunity to get "nightly build" style updates through github desktop.

**Comment by sbrl** [comment]
Those labels look cool, but the pace of WorldEditAdditions is not rushed. I'm in no hurry to work on and merge issues - I follow my inspiration. To this end, I'd prefer to avoid adding those new labels, as I feel they would support a more rushed development process.

### Branches

1. `master` is now `main` in this repository. This is part of a move across the git ecosystem to migrate from potentially offensive words. See [this news article](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main) for more information. There's still a default branch - I've just updated it to follow the new standard.
2. This would indeed help, but for those who want a stable version of the mod should checkout a release or use ContentDB, not checkout directly from `main`. I'll update the README to reflect this.

**Comment by VorTechnix** [comment]
Ok so you're going to still be directly developing on main then?

**Comment by sbrl** [comment]
Yeah, currently that's the way I have been doing things.

**Comment by sbrl** [comment]
It looks like this discussion has been resolved so I'm going to close this issue for now, but I can always re-open if there's more to discuss.
