### ISSUE TITLE
Implement new register_command function

### ISSUE THREAD

**Issue by VorTechnix** [sbrl/Minetest-WorldEditAdditions#47]
The current `worldedit.register_command` function does not pass the `name` parameter to the parse element of the commands it registers. Having looked at the worldedit implementation I think it should be fairly painless to implement a better version of it ourselves. I could be totally wrong and this might turn into a nightmare but I think it's worth trying. Worst case we learn something and revert.

**Comment by sbrl** [comment]
This is a good idea, but unfortunately it would make the implementation of `//multi`, `//subdivide`, and potentially `//many` more complicated. This one is a bit of a rabbit hole.

**Comment by VorTechnix** [comment]
How would make them more complicated? They register straight to minetest and wouldn't be effected.

**Comment by VorTechnix** [comment]
As per conversation on discord this is a nope.
