### ISSUE TITLE
//fillcave bugs

### ISSUE THREAD

**Issue by VorTechnix** [sbrl/Minetest-WorldEditAdditions#50]
Doesn't fill any torus in Minetest 5.4.1.

**Comment by sbrl** [comment]
Hrm, seems to work for me on a Minetest server I have:

```bash
$ minetestserver --version
Minetest 5.4.1-sbrl1 (Linux)
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
STATIC_SHAREDIR="/usr/local/share/minetest"
```

Compiled on Ubuntu Server 20.04 from https://github.com/minetest/minetest/commit/b2596eda32a41a8008b6979d7a29e0c225421a3a

**Comment by sbrl** [comment]
Cleared up via Discord. This was a misunderstanding - I clarified the docs here. If anyone else runs across this issue and finds the docs aren't clear enough, I'll reopen and look at improving them further.
