### ISSUE TITLE
Add allocate, set, load workflow to cookbook

### ISSUE THREAD

**Issue by VorTechnix** [sbrl/Minetest-WorldEditAdditions#65]
@Uberi added `//allocate` to Worldedit to help with the issue that `//load` doesn't restore the air nodes in a saved build. However it's not immediately apparent what it's for if you read his documentation so I purpose adding `//multi //allocate <file> //set air //load <file>` to our cookbook.

**Comment by sbrl** [comment]
Sounds good! Want to open a PR?

**Comment by VorTechnix** [comment]
> Want to open a PR?
Not really. Can't we just hammer out the details here and dump straight into main? It's not *that* big of an addition.

**Comment by sbrl** [comment]
Sure thing, go ahead @VorTechnix

Sorry that's a habit from replying to issues in tldr-pages/tldr haha

**Comment by VorTechnix** [comment]
How's this for the entry:

## Preserve Air During Schematic Load
`//load` only writes non-air blocks in a saved WorldEdit schematic. To get around this the `//allocate` command was created so that users could set the target area to air before the new nodes were written. The following command applies this work flow (replace `<file>` with the name of your schematic before using the command):
```
//multi //allocate <file> //set air //load <file>
```

**Comment by sbrl** [comment]
Sounds great! Feel free to add that to the cookbook. Then I'll update the website :-)

**Comment by VorTechnix** [comment]
19404484a067ed394f38d0f09915316872db3bc9
