### ISSUE TITLE
documentation //maze

### ISSUE THREAD

**Issue by Bastrabun** [sbrl/Minetest-WorldEditAdditions#9]
I assume in the following sentence the term `path_height` should be replaced with the term `path_length`

Note that `path_width` must always be at least 1 less than the `path_height` in order to operate normally.

Sorry to open that many issues, but I feel this project deserves more attention :)

**Comment by sbrl** [comment]
Thanks - great catch! Great documentation is just as important as the project itself.

No problem about the issue count -in fact keeping them as separate issues makes it much easier for me to work on, and I can tackle 1 issue on its own at a time.
