### ISSUE TITLE
CSS issue on Chrome mobile

### ISSUE THREAD

**Issue by CrimsonTome** [sbrl/Minetest-WorldEditAdditions#91]
Issue: Main screen is not centred / lots of blank space that probably is not intentional? Additionally there is text overflow as seen in the screenshot.
Chrome Version: 109.0.5414.117 mobile
OS: Android 10, Huawei POT-LX1

Attached below is a screenshot of <https://worldeditadditions.mooncarrot.space/>
![](https://cdn.discordapp.com/attachments/566616867351953409/1077761103611842571/Screenshot_20230222_005243_com.android.chrome.jpg)

**Comment by sbrl** [comment]
Fixed
