### ISSUE TITLE
logic error due to operator precedence

### ISSUE THREAD

**Issue by fluxionary** [sbrl/Minetest-WorldEditAdditions#93]
https://github.com/sbrl/Minetest-WorldEditAdditions/blob/8652ad6335f2d1576af0f99f759f073496358ad5/worldeditadditions_commands/commands/meta/for.lua#L57

this conditional is always false. i'm not certain what the correct code is.

**Comment by sbrl** [comment]
Fixed in b88cec64d40df3665aed78c5c2fb24e0f421c101
